mysite/myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = "myauth"

urlpatterns = [
    # path("login/", views.login_view, name="login"),
    path("hello/", views.HelloView.as_view(), name="hello"),

    path(
        "login/", 
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ), 
        name="login"
    ),
    path("logout/", views.loguot_view, name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("about-me/", views.AboutMeView.as_view(), name="about-me"),
    path("cookie/get/", views.get_cookie_view, name="cookie-get"),
    path("cookie/set/", views.set_cookie_view, name="cookie-set"),
    path("session/get/", views.get_session_view, name="session-set"),
    path("session/set/", views.set_session_view, name="session-set"),

    path("foo-bar/", views.FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps


urlpatterns = [
    path('admin/doc/', include("django.contrib.admindocs.urls")),
    path('admin/', admin.site.urls),
    path("req/", include("requestdataapp.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path("myauth/", include("myauth.urls")),
    path("shop/", include("shopapp.urls")),
    path("blog/", include("blogapp.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    ),
]

# urlpatterns += i18n_patterns(
#     path("myauth/", include("myauth.urls")),
#     path("shop/", include("shopapp.urls")),
# )

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", views.ProductViewSet)


urlpatterns = [
    path("", views.ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("products/", views.ProductsListView.as_view(), name="products_list"),
    path("products/export/", views.ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/<int:pk>/update/", views.ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", views.OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", views.OrderDetailView.as_view(), name="order_details"),
    path("groups/", views.GroupListView.as_view(), name="groups"),

]

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продовать в интернет-магазине.
    
    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + "..."

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
    )
    products = models.ManyToManyField("Product", related_name="orders")
    receipt = models.FileField(null=True, upload_to="orders/receipts")

mysite/shopapp/forms.py
from django import forms
from django.contrib.auth.models import Group

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "discount", "preview"]

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"allow_multiple_selected": True}),
    )


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()
    

mysite/shopapp/views.py
from csv import DictWriter
from timeit import default_timer
import logging

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from .models import Product, Order, ProductImage
from .forms import ProductForm, GroupForm
from .serializers import ProductSerializer
from .common import save_csv_products


log = logging.getLogger(__name__)


class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })

        return response
    

    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request) -> Response:
        products = save_csv_products(
            file=request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)




class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:

        products = Product.objects.all()

        context = {
            "time_running": default_timer(),
            "products": Product.objects.all(),
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        return render(request, "shopapp/shop-index.html", context=context)


class GroupListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            "shopapp/groups-list.html",
            context={
                "groups": Group.objects.prefetch_related("permissions").all(),
                "form": GroupForm(),
            }
        )
    
    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)
        

class ProductDetailView(DetailView):
    template_name = "shopapp/product-detail.html"
    model = Product
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    # model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = "products"


class ProductCreateView(CreateView):
    # def test_func(self): UserPassesTestMixin,
    #     return self.request.user.is_superuser
    
    model = Product
    fields = ["name", "price", "description", "discount", "preview"]
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UpdateView):
    model = Product
    # fields = ["name", "price", "description", "discount", "preview"]
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self) -> str:
        return reverse(
            "shopapp:product_detail",
            kwargs={"pk": self.object.pk},
        )
    
    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()

        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = Order.objects.select_related("user").prefetch_related("products").all()


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["shopapp.view_order"]
    queryset = Order.objects.select_related("user").prefetch_related("products").all()


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]

        return JsonResponse({"products": products_data})

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Greate</button>
        </form>
    </div>
    <div>
    {% if  not groups %}
        <h3>No groups yet</h3>
    {% else %}
        <ul>

            {% for group in groups %}
                <li>
                    <div>{{group.name}}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{permission.name}}
                                (<code>{{permission.codename}}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
  
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{object.pk}} details
{% endblock %}

{% block body %}
  <h1>Order #{{object.pk}}</h1>
  <div>
    <p>Order by: {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{object.promocode}}</code></p>
    <p>Delivery address: {{object.delivery_address}}</p>
    <div>
    Product in order:
    <ul>
        {% for product in object.products.all %}
            <li>{{product.name}} for ${{product.price}}</li>
        {% endfor %}
    </ul>
    </div>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{order.pk}}</a></p>
          <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{order.promocode}}</code></p>
          <p>Delivery address: {{order.delivery_address}}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{product.name}} for ${{product.price}}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
    <h3>No orders yet</h3>
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product-detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{product.pk}}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{product.name}}</strong></h1>
    <div>
        <div>Description: <em>{{product.description}}</em></div>
        <div>Price: {{product.price}}</div>
        <div>Discount: {{product.discount}}</div>
        <div>Archived: {{product.archived}}</div>
        {% if product.preview %}
          <img src="{{product.preview.url}}" alt="{{product.preview.name}}" width="150" height="100">
        {% endif %}

        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{img.image.url}}" alt="{{img.image.name}}">
                    <div>{{img.description}}</div>
                </div>
            {% empty %}
                <div>No images uploaded yet</div>
            {% endfor %}
        </div>
    </div>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to Product list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Delete archive {{object.name}}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive product: {{object.name}}</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_detail' pk=object.pk %}">Back to product details</a>
    </div>
    <br>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
  <div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">
        Create
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update a product</h1>
  <div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">
        Update
      </button>
    </form>
  </div>

  <div>
    <a href="{% url 'shopapp:product_detail' pk=object.pk %}">Back to product #{{object.pk}}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h2>{% translate 'Products' %}:</h2>
  {% if products %}
  <div>
    {% for product in products %}
      <div>
        <p><a href="{% url 'shopapp:product_detail' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{product.name}}</a></p>
        <p>{% translate 'Price' %}: {{product.price}}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'discount' %}: {% firstof product.discount no_discount %}</p>

        {% if product.preview %}
          <img src="{{product.preview.url}}" alt="{{product.preview.name}}" width="150" height="100">
        {% endif %}
      </div>
    {% endfor %}
  </div>
  {% else %}
  <h3>{% translate 'No products yet' %}</h3>
  {% endif %}

  <div>
    <a href="{% url 'shopapp:product_create' %}">{% translate 'Create a new product' %}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import-products-csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{block.super}}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index</h1>

    <div>
      <ul>
        {% for product in products %}
          <li>{{product}}</li>
        {% endfor %}
      </ul>
    </div>

    <div>
        Time running: {{ time_running }}
    </div>
    <div>
        {% lorem 3 p %}
    </div>
{% endblock %}